// A broad set of public Google Fonts. Selecting one loads it on demand from the
// Google Fonts CSS API (see loadFont in ConfigPanel). Searchable in the picker.
export const GOOGLE_FONTS: string[] = [
  "Inter", "Roboto", "Open Sans", "Lato", "Montserrat", "Poppins", "Raleway", "Nunito",
  "Nunito Sans", "Work Sans", "Source Sans 3", "Manrope", "DM Sans", "Rubik", "Karla",
  "Mulish", "Figtree", "Plus Jakarta Sans", "Onest", "Outfit", "Sora", "Space Grotesk",
  "Lexend", "Epilogue", "Hanken Grotesk", "Instrument Sans", "Geist", "Albert Sans",
  "Be Vietnam Pro", "Red Hat Display", "Red Hat Text", "Public Sans", "IBM Plex Sans",
  "IBM Plex Serif", "IBM Plex Mono", "Archivo", "Archivo Narrow", "Barlow", "Barlow Condensed",
  "Cabin", "Fira Sans", "Fira Code", "Heebo", "Josefin Sans", "Kanit", "Libre Franklin",
  "Bricolage Grotesque", "Schibsted Grotesk", "Unbounded", "Chivo", "Anton", "Bebas Neue",
  "Oswald", "Teko", "Titillium Web", "Exo 2", "Saira", "Saira Condensed", "Jost", "Urbanist",
  "Quicksand", "Comfortaa", "Baloo 2", "Fredoka", "Signika", "Signika Negative", "Assistant",
  "Overpass", "Overpass Mono", "Cairo", "Tajawal", "Almarai", "El Messiri", "Readex Pro",
  "Playfair Display", "Merriweather", "Merriweather Sans", "Lora", "PT Serif", "PT Sans",
  "Noto Sans", "Noto Serif", "Crimson Text", "Crimson Pro", "EB Garamond", "Cormorant",
  "Cormorant Garamond", "Bitter", "Domine", "Spectral", "Zilla Slab", "Roboto Slab",
  "Josefin Slab", "Arvo", "Slabo 27px", "Vollkorn", "Frank Ruhl Libre", "Newsreader",
  "Fraunces", "Source Serif 4", "Libre Baskerville", "Alegreya", "Alegreya Sans",
  "Cardo", "Gelasio", "Literata", "Petrona", "Rozha One", "Yeseva One", "Abril Fatface",
  "DM Serif Display", "DM Serif Text", "Playfair", "Bodoni Moda", "Italiana",
  "Space Mono", "JetBrains Mono", "Roboto Mono", "Source Code Pro", "Inconsolata",
  "Ubuntu", "Ubuntu Mono", "PT Mono", "Cousine", "Azeret Mono", "Martian Mono",
  "Dancing Script", "Pacifico", "Caveat", "Satisfy", "Great Vibes", "Sacramento",
  "Kaushan Script", "Lobster", "Shadows Into Light", "Permanent Marker", "Amatic SC",
  "Indie Flower", "Patrick Hand", "Gloria Hallelujah", "Courgette", "Cookie", "Allura",
  "Righteous", "Fjalla One", "Alfa Slab One", "Passion One", "Staatliches", "Bungee",
  "Russo One", "Orbitron", "Audiowide", "Monoton", "Press Start 2P", "Silkscreen",
  "Playfair Display SC", "Cinzel", "Marcellus", "Forum", "Prata", "Gilda Display",
  "Josefin Sans", "Karla", "Mukta", "Hind", "Hind Siliguri", "Rajdhani", "Dosis",
  "Maven Pro", "Muli", "Catamaran", "Encode Sans", "Encode Sans Condensed", "Sarabun",
  "Prompt", "Mitr", "Pridi", "Chakra Petch", "Krub", "K2D", "Bai Jamjuree", "Nokora",
  "Zen Kaku Gothic New", "Zen Maru Gothic", "M PLUS Rounded 1c", "M PLUS 1p", "Kosugi Maru",
  "Noto Sans JP", "Noto Serif JP", "Sawarabi Mincho", "Shippori Mincho", "Yuji Syuku",
  "Gothic A1", "Do Hyeon", "Jua", "Nanum Gothic", "Nanum Myeongjo", "Black Han Sans",
  "Gowun Dodum", "Gowun Batang", "Song Myung", "Stylish", "Sunflower", "Poor Story",
];
